#' Convert a PDF file to PDF/A file with a particular flavor (e.g. "2b")
#'
#' @param pdf_path
#' @param save_to
#' @param pdf_flavor
#'
#' @returns
#' @export
#'
#' @examples
#' @keywords internal


# FIND VERAPDF ---------------------------------------------------------------

.check_verapdf_available <- function() {
  config_file <- file.path(
    tools::R_user_dir("eatArchive", "config"),
    "verapdf_path.txt"
  )

  # 1) Use the manually configured path
  if (file.exists(config_file)) {
    verapdf_path <- readLines(
      config_file,
      n = 1L,
      warn = FALSE
    )

    if (
      length(verapdf_path) == 1L &&
      nzchar(verapdf_path) &&
      file.exists(verapdf_path)
    ) {
      return(verapdf_path)
    }
  }

  # 2) Search the system PATH
  hits <- Sys.which(c(
    "verapdf",
    "verapdf.bat",
    "verapdf.sh"
  ))

  hits <- unname(hits[nzchar(hits)])

  if (length(hits) > 0L && file.exists(hits[[1L]])) {
    return(hits[[1L]])
  }

  # 3) veraPDF is unavailable
  message(
    "veraPDF was not found. PDF/A validation and conversion will be skipped.\n",
    "Install veraPDF from https://verapdf.org/software/.\n",
    "Already installed? Run eatArchive::set_verapdf() to select its folder."
  )

  NA_character_
}
# .check_verapdf_available


# HELPER FUNCTIONS ---------------------------------------------------------------
#
# .find_icc <- function() {
#   icc <- system.file("extdata", "sRGB2014.icc", package = "eatArchive")
#   if (!nzchar(icc) || !file.exists(icc)) return("")
#   icc
# }
#
# # .find_icc()
#
#
# .find_ghostscript <- function() {
#   candidates <- c(Sys.which("gswin64c.exe"), Sys.which("gs"))
#   gs <- candidates[nzchar(candidates)][1]
#   if (!nzchar(gs)) return("")
#   gs
# }
# # .find_ghostscript()
#
#
# .verapdf_cache <- new.env(parent = emptyenv())
# .check_verapdf_available <- function() {
#
#   # 1) Check if already cached in this session?
#   p <- .verapdf_cache$path
#   if (is.character(p) && length(p) == 1L && nzchar(p) && file.exists(p)) {
#     return(p)
#   }
#
#   # 2) Check if on PATH?
#   hits <- Sys.which(c("verapdf", "verapdf.bat", "verapdf.sh"))
#   hits <- unname(hits[nzchar(hits)])
#   if (length(hits) > 0 && file.exists(hits[[1]])) {
#     .verapdf_cache$path <- hits[[1]]
#     return(hits[[1]])
#   }
#
#   # 3) Not found -> install via checkpdf (LOUD, by design)
#   if (!requireNamespace("checkpdf", quietly = TRUE)) {
#     stop(
#       "Package 'checkpdf' is required to install veraPDF. Please install it first:\n",
#       "devtools::install_github('rfortherestofus/checkpdf')",
#       call. = FALSE
#     )
#   }
#
#   res <- checkpdf::install_verapdf()
#   verapdf_path <- unname(res[[1]])
#
#   if (!is.character(verapdf_path) ||
#       length(verapdf_path) != 1L ||
#       !nzchar(verapdf_path) ||
#       !file.exists(verapdf_path)) {
#     stop(
#       "veraPDF installation did not return a usable path. ",
#       "Please run checkpdf::install_verapdf() manually and restart R.",
#       call. = FALSE
#     )
#   }
#
#   .verapdf_cache$path <- verapdf_path
#   verapdf_path
# }
# # # Test:
# # .check_verapdf_available()
#
#
# .wait_for_file <- function(path, tries = 15L, sleep = 0.2) {
#   for (i in seq_len(tries)) {
#     if (file.exists(path)) return(TRUE)
#     Sys.sleep(sleep)
#   }
#   FALSE
# }
#
# # This is a function for creating a temporary ghostscript file, including the actual paths.
# # A "permanent" .ps-file didn't (always) produce the correct outcome
# .write_pdfa_def_pdfmark <- function(icc_path, part = 2L) {
#   icc_path <- normalizePath(icc_path, winslash = "/", mustWork = FALSE)
#   part <- as.integer(part)
#
#   s_key <- paste0("/GTS_PDFA", part)
#
#   lines <- c(
#     "%!",
#     "% PDF/A pdfmark definition (generated by R)",
#     sprintf("/ICCProfile (%s) def", icc_path),
#     "",
#     "% Define ICC profile stream",
#     "[ /_objdef {icc_PDFA} /type /stream /OBJ pdfmark",
#     "[ {icc_PDFA} <</N 3>> /PUT pdfmark",
#     "[ {icc_PDFA} ICCProfile (r) file /PUT pdfmark",
#     "",
#     "% Define OutputIntent dictionary",
#     "[ /_objdef {OutputIntent_PDFA} /type /dict /OBJ pdfmark",
#     sprintf("[ {OutputIntent_PDFA} <</Type /OutputIntent /S %s /DestOutputProfile {icc_PDFA}", s_key),
#     "  /OutputConditionIdentifier (sRGB IEC61966-2.1)",
#     "  /Info (sRGB IEC61966-2.1)",
#     "  /RegistryName (http://www.color.org)",
#     ">> /PUT pdfmark",
#     "",
#     "% Attach OutputIntent to the catalog",
#     "[ {Catalog} <</OutputIntents [ {OutputIntent_PDFA} ]>> /PUT pdfmark"
#   )
#
#   f <- tempfile("PDFA_def_", fileext = ".ps")
#   writeLines(lines, f, useBytes = TRUE)
#   f
# }
#
# .run_gs_pdfa <- function(gs,
#                          pdf_path,
#                          outfile,
#                          part,
#                          icc,
#                          notransparency = FALSE) {
#
#   if (!nzchar(gs)) stop("Ghostscript not found (gswin64c.exe).", call. = FALSE)
#
#   pdf_path_n <- normalizePath(pdf_path, winslash = "/", mustWork = TRUE)
#   out_path_n <- normalizePath(outfile, winslash = "/", mustWork = FALSE)
#   icc_n <- normalizePath(icc, winslash = "/", mustWork = FALSE)
#
#   def_ps <- .write_pdfa_def_pdfmark(icc_n, part = part)
#   def_ps_n <- normalizePath(def_ps, winslash = "/", mustWork = TRUE)
#
#   # NOTE: Don't shQuote() the -f file arguments on Windows (avoids /undefinedfilename issues).
#   args <- c(
#     "-dSAFER",
#     paste0("-dPDFA=", part),
#     "-dPDFACompatibilityPolicy=1",
#     "-sDEVICE=pdfwrite",
#     "-dBATCH", "-dNOPAUSE",
#     "-dEmbedAllFonts=true",
#     "-dSubsetFonts=true",
#     paste0("-sOutputFile=", shQuote(out_path_n)),
#     "-f", def_ps_n, pdf_path_n
#   )
#
#   out <- suppressWarnings(system2(gs, args = args, stdout = TRUE, stderr = TRUE))
#   exit <- attr(out, "status")
#   if (is.null(exit)) exit <- 0L
#
#   unlink(def_ps, force = TRUE)
#
#   reverted <- any(grepl("reverting to normal PDF output", out, ignore.case = TRUE))
#
#   list(
#     exit_code = as.integer(exit),
#     reverted = reverted,
#     log = out
#   )
# }
#
#
# .check_pdf_flavor <- function(file,
#                               flavor = "2b",
#                               verapdf_path) {
#
#   if (!is.character(verapdf_path) || !nzchar(verapdf_path) || !file.exists(verapdf_path)) {
#     return(FALSE)
#   }
#
#   xml_lines <- suppressWarnings(system2(
#     verapdf_path,
#     args   = c("--loglevel", "0", "--format", "xml", "-f", flavor, shQuote(file)),
#     stdout = TRUE,
#     stderr = FALSE
#   ))
#
#   line <- xml_lines[
#     grepl("<validationReport\\b", xml_lines) &
#       grepl("isCompliant=", xml_lines)
#   ][1]
#
#   !is.na(line) && grepl('isCompliant="true"', line)
# }
# # .check_pdf_flavor("C:/R/eatArchive_lokal/PDF/PISA_2022_Datenbereitstellungsvertrag_1b.pdf",
# #                   "2b",
# #                   "C:\\Users\\buchjani/verapdf/verapdf.bat")
#
#
#
# ### MAIN FUNCTIONS ----
#
# # quick and simple: tries to convert, but only tries once
# .convert_pdf_to_pdfa_quick <- function(pdf_path,
#                                        save_to,
#                                        pdf_flavor = "2b") {
#
#   # minimal input validation
#   if (!file.exists(pdf_path)) stop("Input PDF not found: ", pdf_path, call. = FALSE)
#
#   icc <- .find_icc()
#   if (!nzchar(icc)) stop("Internal ICC profile not found in installed package.", call. = FALSE)
#
#   gs <- .find_ghostscript()
#   if (!nzchar(gs)) stop("Ghostscript not found.", call. = FALSE)
#
#   verapdf_path <- .check_verapdf_available()
#
#   # output directory
#   if (!dir.exists(save_to)) dir.create(save_to, recursive = TRUE)
#
#   # naming
#   base <- basename(pdf_path)
#   base_converted <- sub("\\.pdf$", "_pdfa.pdf", base, ignore.case = TRUE)
#   base_converted <- .fix_umlaut(base_converted)
#   outfile <- file.path(save_to, base_converted)
#
#   # PDF/A flavor
#   part <- as.integer(substr(pdf_flavor, 1, 1))
#   conf <- substr(pdf_flavor, 2, 2)
#
#   if (conf == "a") {
#     warning(
#       "Target flavor 'PDF/A-", part, "a' requires a tagged (structured) PDF; ",
#       "Ghostscript usually does not create tags. Validate output with veraPDF.",
#       call. = FALSE
#     )
#   }
#
#   # overwrite if exists
#   if (file.exists(outfile)) file.remove(outfile)
#
#   # run Ghostscript once
#   pdf_path_n <- normalizePath(pdf_path, winslash = "/", mustWork = TRUE)
#   out_path_n <- normalizePath(outfile, winslash = "/", mustWork = FALSE)
#   icc_n <- normalizePath(icc, winslash = "/", mustWork = TRUE)
#
#   pdaf_def_tmp <- .write_pdfa_def_pdfmark(icc_n, part = part)
#   pdaf_def_n <- normalizePath(pdaf_def_tmp, winslash = "/", mustWork = TRUE)
#
#   args <- c(
#     "-dSAFER",
#     paste0("-dPDFA=", part),
#     "-dPDFACompatibilityPolicy=1",
#     "-sDEVICE=pdfwrite",
#     "-dBATCH", "-dNOPAUSE",
#     "-dEmbedAllFonts=true",
#     "-dSubsetFonts=true",
#     paste0("-sOutputFile=", shQuote(out_path_n)),
#     "-f", pdaf_def_n, pdf_path_n
#   )
#
#   suppressWarnings(system2(gs, args = args, stdout = TRUE, stderr = TRUE))
#   unlink(pdaf_def_tmp, force = TRUE)
#
#   # if no file -> NA
#   if (!file.exists(outfile)) return(NA_character_)
#
#   # validate; if fail, delete and return NA
#   ok <- isTRUE(.check_pdf_flavor(outfile, flavor = pdf_flavor, verapdf_path = verapdf_path))
#
#   if (ok) {
#     outfile
#   } else {
#     if (file.exists(outfile)) file.remove(outfile)
#     NA_character_
#   }
# }
#
#
# # Test:
# # .convert_pdf_to_pdfa_quick(
# #   pdf_path = "C:/R/eatArchive_lokal/PDF/PISA_2022_Datenbereitstellungsvertrag.pdf",
# #   save_to = "C:/R/eatArchive_lokal/PDF",
# #   pdf_flavor = "2b")
#
#
# ## Two-step function
# .convert_pdf_to_pdfa_two_step <- function(pdf_path,
#                                           save_to,
#                                           pdf_flavor = "2b") {
#
#   # minimal input validation
#   if (!file.exists(pdf_path)) stop("Input PDF not found: ", pdf_path, call. = FALSE)
#
#   icc <- .find_icc()
#   if (!nzchar(icc)) stop("Internal ICC profile not found in installed package.", call. = FALSE)
#
#   gs <- .find_ghostscript()
#   if (!nzchar(gs)) stop("Ghostscript not found.", call. = FALSE)
#
#   verapdf_path <- .check_verapdf_available()
#
#   # output directory
#   if (!dir.exists(save_to)) dir.create(save_to, recursive = TRUE)
#
#   # naming
#   base <- basename(pdf_path)
#   base_converted <- sub("\\.pdf$", "_pdfa.pdf", base, ignore.case = TRUE)
#   base_converted <- .fix_umlaut(base_converted)
#   outfile <- file.path(save_to, base_converted)
#
#   part <- as.integer(substr(pdf_flavor, 1, 1))
#   conf <- substr(pdf_flavor, 2, 2)
#
#   if (conf == "a") {
#     warning(
#       "Target flavor 'PDF/A-", part, "a' requires a tagged (structured) PDF; ",
#       "Ghostscript usually does not create tags. Validate output with veraPDF.",
#       call. = FALSE
#     )
#   }
#
#   ## Attempt 1: normal ----
#
#   if (file.exists(outfile)) file.remove(outfile)
#
#   gs1 <- .run_gs_pdfa(
#     gs = gs,
#     pdf_path = pdf_path,
#     outfile = outfile,
#     part = part,
#     icc = icc,
#     notransparency = FALSE
#   )
#
#   # Wait for network drive visibility; validate if present
#   if (.wait_for_file(outfile, tries = 15L, sleep = 0.2)) {
#     ok1 <- isTRUE(.check_pdf_flavor(outfile, flavor = pdf_flavor, verapdf_path = verapdf_path))
#     if (ok1 && !isTRUE(gs1$reverted)) return(outfile)
#   }
#
#   ## Attempt 2: flatten transparency ----
#
#   if (file.exists(outfile)) file.remove(outfile)
#
#   gs2 <- .run_gs_pdfa(
#     gs = gs,
#     pdf_path = pdf_path,
#     outfile = outfile,
#     part = part,
#     icc = icc,
#     notransparency = TRUE
#   )
#
#   if (.wait_for_file(outfile, tries = 15L, sleep = 0.2)) {
#     ok2 <- isTRUE(.check_pdf_flavor(outfile, flavor = pdf_flavor, verapdf_path = verapdf_path))
#     if (ok2 && !isTRUE(gs2$reverted)) return(outfile)
#   }
#
#   if (file.exists(outfile)) file.remove(outfile)
#   NA_character_
# }
#
# # Test:
# # .convert_pdf_to_pdfa_two_step(
# #   pdf_path = "C:/R/eatArchive_lokal/PDF/PISA_2022_Datenbereitstellungsvertrag.pdf",
# #   save_to = "C:/R/eatArchive_lokal/PDF",
# #   pdf_flavor = "2b")
#
